<?= $this->extend('admin/layout') ?>
<?= $this->section('styles') ?>
<link rel="stylesheet" href="<?= base_url('assets/css/admin-photo-gallery.css') ?>">
<?= $this->endSection() ?>
<?= $this->section('content') ?>
<?php $editing = isset($work); ?>
<div class="mb-4"><h2><?= esc($title) ?></h2><a class="btn btn-sm btn-outline-secondary" href="<?= site_url('admin/fotos') ?>">Voltar ao acervo</a></div>
<?php if (session('errors')): ?><div class="alert alert-danger"><ul class="mb-0"><?php foreach (session('errors') as $error): ?><li><?= esc($error) ?></li><?php endforeach ?></ul></div><?php endif ?>
<form method="post" action="<?= $editing ? site_url('admin/fotos/' . $work['id']) : site_url('admin/fotos') ?>" class="card bg-dark border-secondary"><div class="card-body row g-3"><?php if ($editing): ?><input type="hidden" name="_method" value="PUT"><?php endif ?>
<div class="col-md-8"><label class="form-label">Título</label><input required name="title" class="form-control bg-black text-white border-secondary" value="<?= old('title', $work['title'] ?? '') ?>"></div><div class="col-md-4"><label class="form-label">Slug</label><input name="slug" class="form-control bg-black text-white border-secondary" value="<?= old('slug', $work['slug'] ?? '') ?>" placeholder="gerado pelo título"></div>
<div class="col-12"><label class="form-label">Descrição curta</label><textarea name="short_description" rows="2" class="form-control bg-black text-white border-secondary"><?= old('short_description', $work['short_description'] ?? '') ?></textarea></div>
<div class="col-12"><label class="form-label">História da galeria</label><textarea name="story" rows="7" class="form-control bg-black text-white border-secondary"><?= old('story', $work['story'] ?? '') ?></textarea></div>
<div class="col-md-4"><label class="form-label">Data da obra</label><input type="date" name="work_date" class="form-control bg-black text-white border-secondary" value="<?= old('work_date', $work['work_date'] ?? '') ?>"></div><div class="col-md-4"><label class="form-label">Local</label><input name="location" class="form-control bg-black text-white border-secondary" value="<?= old('location', $work['location'] ?? '') ?>"></div><div class="col-md-4"><label class="form-label">Técnica / processo</label><input name="technique" class="form-control bg-black text-white border-secondary" value="<?= old('technique', $work['technique'] ?? '') ?>"></div>
<div class="col-md-5"><label class="form-label">Coleção / tema</label><input name="collection_name" class="form-control bg-black text-white border-secondary" value="<?= old('collection_name', $work['collection_name'] ?? '') ?>"></div><div class="col-md-5"><label class="form-label">Créditos</label><input name="credits" class="form-control bg-black text-white border-secondary" value="<?= old('credits', $work['credits'] ?? '') ?>"></div><div class="col-md-2"><label class="form-label">Ordem</label><input type="number" name="display_order" class="form-control bg-black text-white border-secondary" value="<?= old('display_order', $work['display_order'] ?? 0) ?>"></div>
<div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="is_published" value="1" id="published" <?= old('is_published', $work['is_published'] ?? 0) ? 'checked' : '' ?>><label class="form-check-label" for="published">Publicar no acervo</label></div><div class="col-12"><button class="btn btn-primary">Salvar galeria</button><?php if ($editing): ?><a class="btn btn-outline-info" href="<?= site_url('admin/fotos/' . $work['id'] . '/imagens') ?>">Gerenciar fotografias</a><?php endif ?></div></div></form>
<?= $this->endSection() ?>
