<?= $this->extend('admin/layout') ?>
<?= $this->section('styles') ?>
<link rel="stylesheet" href="<?= base_url('assets/css/admin-photo-gallery.css') ?>">
<?= $this->endSection() ?>
<?= $this->section('content') ?>
<div class="mb-4"><h2>Fotografias: <?= esc($work['title']) ?></h2><a class="btn btn-sm btn-outline-secondary" href="<?= site_url('admin/fotos') ?>">Voltar ao acervo</a></div>
<form method="post" enctype="multipart/form-data" action="<?= site_url('admin/fotos/' . $work['id'] . '/imagens') ?>" class="card bg-dark border-secondary mb-4"><div class="card-body row g-3 align-items-end"><div class="col-md-5"><label class="form-label">Versão web *</label><input required type="file" accept="image/jpeg,image/png,image/webp" name="image" class="form-control bg-black text-white border-secondary"><small class="text-muted">JPG, PNG ou WebP de até 5 MB. Esta versão aparece na galeria e no compartilhamento.</small></div><div class="col-md-5"><label class="form-label">Original para impressão</label><input type="file" accept="image/jpeg,image/png,image/webp" name="original" class="form-control bg-black text-white border-secondary"><small class="text-muted">Opcional, privado, até 25 MB. Não aparece no site.</small></div><div class="col-md-4"><label class="form-label">Título da obra</label><input name="title" class="form-control bg-black text-white border-secondary" placeholder="Nome específico da fotografia"></div><div class="col-md-4"><label class="form-label">Descrição curta</label><input name="description" class="form-control bg-black text-white border-secondary" placeholder="Frase curta para compartilhamento"></div><div class="col-md-3"><label class="form-label">Texto alternativo</label><input name="alt_text" class="form-control bg-black text-white border-secondary"></div><div class="col-md-1"><label class="form-label">Ordem</label><input type="number" name="display_order" min="1" value="<?= (int) $nextDisplayOrder ?>" class="form-control bg-black text-white border-secondary"><small class="text-muted">Próxima</small></div><div class="col-md-2"><button class="btn btn-primary w-100">Enviar</button></div></div></form>
<div class="row g-3"><?php foreach ($images as $image): ?><div class="col-md-4"><div class="card bg-dark border-secondary h-100"><div class="admin-photo-preview"><img src="<?= base_url($image['image_path']) ?>" alt="<?= esc($image['alt_text']) ?>"></div><div class="card-body"><form method="post" action="<?= site_url('admin/fotos/' . $work['id'] . '/imagens/' . $image['id'] . '/metadados') ?>" class="mb-3"><label class="form-label small">Título da obra</label><input name="title" value="<?= esc($image['title'] ?? '') ?>" class="form-control form-control-sm bg-black text-white border-secondary mb-2"><label class="form-label small">Descrição curta</label><textarea name="description" rows="2" class="form-control form-control-sm bg-black text-white border-secondary mb-2"><?= esc($image['description'] ?? '') ?></textarea><label class="form-label small">Texto alternativo</label><input name="alt_text" value="<?= esc($image['alt_text'] ?? '') ?>" class="form-control form-control-sm bg-black text-white border-secondary mb-2"><button class="btn btn-sm btn-outline-light">Salvar metadados</button></form><?php if ($image['is_cover']): ?><span class="badge bg-warning text-dark">Capa</span><?php else: ?><form class="d-inline" method="post" action="<?= site_url('admin/fotos/' . $work['id'] . '/imagens/' . $image['id'] . '/capa') ?>"><button class="btn btn-sm btn-outline-warning">Definir capa</button></form><?php endif ?> <?php if (!empty($image['original_path'])): ?><span class="badge bg-info text-dark">Original arquivado</span><?php endif ?> <a class="btn btn-sm btn-outline-success" href="<?= site_url('admin/fotos/' . $work['id'] . '/imagens/' . $image['id'] . '/edicoes') ?>"><?= $image['is_for_sale'] ? 'Edições à venda' : 'Colocar à venda' ?></a><form class="d-inline" method="post" action="<?= site_url('admin/fotos/' . $work['id'] . '/imagens/' . $image['id'] . '/excluir') ?>" onsubmit="return confirm('Excluir imagem?')"><button class="btn btn-sm btn-outline-danger">Excluir</button></form></div></div></div><?php endforeach ?></div>
<?= $this->endSection() ?>
